[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:socket_app --host 0.0.0.0 --port $PORT" 