[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["sh -c 'cd backend && pip install -r requirements.txt'"]

[start]
cmd = "sh -c 'cd backend && uvicorn main:socket_app --host 0.0.0.0 --port $PORT'" 